import Foundation

private let imageExtensions: Set<String> = [
    "png", "jpg", "jpeg", "webp", "gif", "svg", "avif", "bmp", "tif", "tiff"
]
private let fontExtensions: Set<String> = [
    "ttf", "otf", "woff", "woff2", "eot"
]
private let swiftKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
    "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
    "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case", "catch",
    "continue", "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in",
    "repeat", "return", "throw", "switch", "where", "while", "as", "Any", "false", "is", "nil",
    "self", "Self", "super", "throws", "true", "try", "_", "Type", "Protocol"
]

@main
struct SHTMLAssetNameGen {
    static func main() throws {
        let args = CommandLine.arguments
        guard args.count == 4 else {
            fputs("Usage: shtml-asset-name-gen <images-dir> <fonts-dir> <output-dir>\n", stderr)
            Foundation.exit(2)
        }

        let imagesDir = args[1]
        let fontsDir = args[2]
        let outputDir = args[3]

        try FileManager.default.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

        let imageSymbols = try symbols(in: imagesDir, allowedExtensions: imageExtensions)
        let fontSymbols = try symbols(in: fontsDir, allowedExtensions: fontExtensions)

        try renderExtension(typeName: "ImageName", symbols: imageSymbols)
            .write(
                to: URL(fileURLWithPath: outputDir).appendingPathComponent("ImageName+Generated.swift"),
                atomically: true,
                encoding: .utf8
            )

        try renderExtension(typeName: "FontName", symbols: fontSymbols)
            .write(
                to: URL(fileURLWithPath: outputDir).appendingPathComponent("FontName+Generated.swift"),
                atomically: true,
                encoding: .utf8
            )
    }

    private static func symbols(in directory: String, allowedExtensions: Set<String>) throws -> [(String, String)] {
        guard FileManager.default.fileExists(atPath: directory) else { return [] }

        let fileNames = try FileManager.default.contentsOfDirectory(atPath: directory)
        let baseNames = fileNames.compactMap { file -> String? in
            let url = URL(fileURLWithPath: file)
            guard allowedExtensions.contains(url.pathExtension.lowercased()) else { return nil }
            return url.deletingPathExtension().lastPathComponent
        }.sorted()

        var used = Set<String>()
        return baseNames.map { base in
            var id = swiftIdentifier(from: base)
            if used.contains(id) {
                var n = 2
                while used.contains("\(id)\(n)") {
                    n += 1
                }
                id = "\(id)\(n)"
            }
            used.insert(id)
            return (id, base)
        }
    }

    private static func swiftIdentifier(from raw: String) -> String {
        let parts = raw
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map(String.init)
            .filter { !$0.isEmpty }

        guard let first = parts.first else { return "asset" }

        let head = first.prefix(1).lowercased() + first.dropFirst()
        let tail = parts.dropFirst().map { part in
            part.prefix(1).uppercased() + part.dropFirst()
        }.joined()

        var identifier = head + tail
        if let firstChar = identifier.first, firstChar.isNumber {
            identifier = "_\(identifier)"
        }
        if swiftKeywords.contains(identifier) {
            return "`\(identifier)`"
        }
        return identifier
    }

    private static func renderExtension(typeName: String, symbols: [(String, String)]) -> String {
        let members = symbols
            .map { "    static let \($0.0): \(typeName) = \"\($0.1)\"" }
            .joined(separator: "\n")

        return """
        // Generated by SHTML asset-name-gen. Do not edit.
        import SHTML

        extension \(typeName) {
        \(members)
        }
        """
    }
}
