// Type-safe color representation
public enum Color: Sendable {
    case hex(String)
    case rgb(Int, Int, Int)
    case rgba(Int, Int, Int, Double)
    case hsl(Int, Int, Int)
    case hsla(Int, Int, Int, Double)
    case named(String)
    
    public var css: String {
        switch self {
        case .hex(let value):
            return value.hasPrefix("#") ? value : "#\(value)"
        case .rgb(let r, let g, let b):
            return "rgb(\(r), \(g), \(b))"
        case .rgba(let r, let g, let b, let a):
            return "rgba(\(r), \(g), \(b), \(a))"
        case .hsl(let h, let s, let l):
            return "hsl(\(h), \(s)%, \(l)%)"
        case .hsla(let h, let s, let l, let a):
            return "hsla(\(h), \(s)%, \(l)%, \(a))"
        case .named(let name):
            return name
        }
    }
    
    // Basic colors
    public static let black = Color.named("black")
    public static let white = Color.named("white")
    public static let red = Color.named("red")
    public static let green = Color.named("green")
    public static let blue = Color.named("blue")
    public static let yellow = Color.named("yellow")
    public static let orange = Color.named("orange")
    public static let purple = Color.named("purple")
    public static let pink = Color.named("pink")
    public static let cyan = Color.named("cyan")
    public static let gray = Color.named("gray")
    public static let transparent = Color.named("transparent")
    
    // Extended CSS named colors
    public static let aliceblue = Color.named("aliceblue")
    public static let antiquewhite = Color.named("antiquewhite")
    public static let aqua = Color.named("aqua")
    public static let aquamarine = Color.named("aquamarine")
    public static let azure = Color.named("azure")
    public static let beige = Color.named("beige")
    public static let bisque = Color.named("bisque")
    public static let blanchedalmond = Color.named("blanchedalmond")
    public static let blueviolet = Color.named("blueviolet")
    public static let brown = Color.named("brown")
    public static let burlywood = Color.named("burlywood")
    public static let cadetblue = Color.named("cadetblue")
    public static let chartreuse = Color.named("chartreuse")
    public static let chocolate = Color.named("chocolate")
    public static let coral = Color.named("coral")
    public static let cornflowerblue = Color.named("cornflowerblue")
    public static let cornsilk = Color.named("cornsilk")
    public static let crimson = Color.named("crimson")
    public static let darkblue = Color.named("darkblue")
    public static let darkcyan = Color.named("darkcyan")
    public static let darkgoldenrod = Color.named("darkgoldenrod")
    public static let darkgray = Color.named("darkgray")
    public static let darkgreen = Color.named("darkgreen")
    public static let darkgrey = Color.named("darkgrey")
    public static let darkkhaki = Color.named("darkkhaki")
    public static let darkmagenta = Color.named("darkmagenta")
    public static let darkolivegreen = Color.named("darkolivegreen")
    public static let darkorange = Color.named("darkorange")
    public static let darkorchid = Color.named("darkorchid")
    public static let darkred = Color.named("darkred")
    public static let darksalmon = Color.named("darksalmon")
    public static let darkseagreen = Color.named("darkseagreen")
    public static let darkslateblue = Color.named("darkslateblue")
    public static let darkslategray = Color.named("darkslategray")
    public static let darkslategrey = Color.named("darkslategrey")
    public static let darkturquoise = Color.named("darkturquoise")
    public static let darkviolet = Color.named("darkviolet")
    public static let deeppink = Color.named("deeppink")
    public static let deepskyblue = Color.named("deepskyblue")
    public static let dimgray = Color.named("dimgray")
    public static let dimgrey = Color.named("dimgrey")
    public static let dodgerblue = Color.named("dodgerblue")
    public static let firebrick = Color.named("firebrick")
    public static let floralwhite = Color.named("floralwhite")
    public static let forestgreen = Color.named("forestgreen")
    public static let fuchsia = Color.named("fuchsia")
    public static let gainsboro = Color.named("gainsboro")
    public static let ghostwhite = Color.named("ghostwhite")
    public static let gold = Color.named("gold")
    public static let goldenrod = Color.named("goldenrod")
    public static let greenyellow = Color.named("greenyellow")
    public static let grey = Color.named("grey")
    public static let honeydew = Color.named("honeydew")
    public static let hotpink = Color.named("hotpink")
    public static let indianred = Color.named("indianred")
    public static let indigo = Color.named("indigo")
    public static let ivory = Color.named("ivory")
    public static let khaki = Color.named("khaki")
    public static let lavender = Color.named("lavender")
    public static let lavenderblush = Color.named("lavenderblush")
    public static let lawngreen = Color.named("lawngreen")
    public static let lemonchiffon = Color.named("lemonchiffon")
    public static let lightblue = Color.named("lightblue")
    public static let lightcoral = Color.named("lightcoral")
    public static let lightcyan = Color.named("lightcyan")
    public static let lightgoldenrodyellow = Color.named("lightgoldenrodyellow")
    public static let lightgray = Color.named("lightgray")
    public static let lightgreen = Color.named("lightgreen")
    public static let lightgrey = Color.named("lightgrey")
    public static let lightpink = Color.named("lightpink")
    public static let lightsalmon = Color.named("lightsalmon")
    public static let lightseagreen = Color.named("lightseagreen")
    public static let lightskyblue = Color.named("lightskyblue")
    public static let lightslategray = Color.named("lightslategray")
    public static let lightslategrey = Color.named("lightslategrey")
    public static let lightsteelblue = Color.named("lightsteelblue")
    public static let lightyellow = Color.named("lightyellow")
    public static let lime = Color.named("lime")
    public static let limegreen = Color.named("limegreen")
    public static let linen = Color.named("linen")
    public static let magenta = Color.named("magenta")
    public static let maroon = Color.named("maroon")
    public static let mediumaquamarine = Color.named("mediumaquamarine")
    public static let mediumblue = Color.named("mediumblue")
    public static let mediumorchid = Color.named("mediumorchid")
    public static let mediumpurple = Color.named("mediumpurple")
    public static let mediumseagreen = Color.named("mediumseagreen")
    public static let mediumslateblue = Color.named("mediumslateblue")
    public static let mediumspringgreen = Color.named("mediumspringgreen")
    public static let mediumturquoise = Color.named("mediumturquoise")
    public static let mediumvioletred = Color.named("mediumvioletred")
    public static let midnightblue = Color.named("midnightblue")
    public static let mintcream = Color.named("mintcream")
    public static let mistyrose = Color.named("mistyrose")
    public static let moccasin = Color.named("moccasin")
    public static let navajowhite = Color.named("navajowhite")
    public static let navy = Color.named("navy")
    public static let oldlace = Color.named("oldlace")
    public static let olive = Color.named("olive")
    public static let olivedrab = Color.named("olivedrab")
    public static let orangered = Color.named("orangered")
    public static let orchid = Color.named("orchid")
    public static let palegoldenrod = Color.named("palegoldenrod")
    public static let palegreen = Color.named("palegreen")
    public static let paleturquoise = Color.named("paleturquoise")
    public static let palevioletred = Color.named("palevioletred")
    public static let papayawhip = Color.named("papayawhip")
    public static let peachpuff = Color.named("peachpuff")
    public static let peru = Color.named("peru")
    public static let plum = Color.named("plum")
    public static let powderblue = Color.named("powderblue")
    public static let rebeccapurple = Color.named("rebeccapurple")
    public static let rosybrown = Color.named("rosybrown")
    public static let royalblue = Color.named("royalblue")
    public static let saddlebrown = Color.named("saddlebrown")
    public static let salmon = Color.named("salmon")
    public static let sandybrown = Color.named("sandybrown")
    public static let seagreen = Color.named("seagreen")
    public static let seashell = Color.named("seashell")
    public static let sienna = Color.named("sienna")
    public static let silver = Color.named("silver")
    public static let skyblue = Color.named("skyblue")
    public static let slateblue = Color.named("slateblue")
    public static let slategray = Color.named("slategray")
    public static let slategrey = Color.named("slategrey")
    public static let snow = Color.named("snow")
    public static let springgreen = Color.named("springgreen")
    public static let steelblue = Color.named("steelblue")
    public static let tan = Color.named("tan")
    public static let teal = Color.named("teal")
    public static let thistle = Color.named("thistle")
    public static let tomato = Color.named("tomato")
    public static let turquoise = Color.named("turquoise")
    public static let violet = Color.named("violet")
    public static let wheat = Color.named("wheat")
    public static let whitesmoke = Color.named("whitesmoke")
    public static let yellowgreen = Color.named("yellowgreen")
}
